# Copyright 20 The original authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
name: Build

# We need to set these defaults so that .bashrc is called for each step.
# This is needed so that sdkman can be properly intialized
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Haskell with ghc ${{ matrix.ghc-version }} and cabal ${{ matrix.cabal-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: [8.4.4]
        cabal-version: [3.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}
          enable-stack: true
          stack-version: 'latest'
      - name: Build
        run: stack build
      - name: Run tests
        run: stack test
